<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
    <ApplicationUseCompatibleTextRendering>false</ApplicationUseCompatibleTextRendering>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <AssemblyName>ReduceForYouTube</AssemblyName>
    <RootNamespace>MediaSuite.Tools.ReduceForYouTube</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaSuite.Core\MediaSuite.Core.csproj" />
  </ItemGroup>

</Project>
