<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>MediaSuiteManager</AssemblyName>
    <RootNamespace>MediaSuite.Manager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaSuite.Core\MediaSuite.Core.csproj" />
  </ItemGroup>

</Project>
